spring:
  datasource:
    url: ${DEV_MYSQL_HOST}
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${DEV_MONGODB_URI}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${DEV_S3_ACCESS_KEY}
        secret-key: ${DEV_S3_SECRET_KEY}
      s3:
        bucket: ${DEV_S3_BUCKET_NAME}

logging:
  level:
    org.springframework.data.redis: DEBUG

swagger:
  server:
    url: ${DEV_SWAGGER_URL}

kakao:
  admin-key: ${DEV_KAKAO_ADMIN_KEY}