spring:
  profiles:
    active: local

---
server:
  port: 8080

---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: false
---

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expired-in: 2592000000    # 30일
  refresh-expired-in: 2592000000   # 30일

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: default
    persist-authorization: true
    display-request-duration: true

---
kakao:
  api:
    url:
      user-info: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink

---
ai:
  server:
    url: ${AI_SERVER_URL}

---
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
